import { createServerActionClient } from '@supabase/auth-helpers-nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { cookies } from 'next/headers'
import Logout from './auth/logout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerActionClient<Database>({ cookies });
  let salutation = 'Home'
  const { data: { session } } = await supabase.auth.getSession();

  if (session) {

    const { data: profile, error } = await supabase.from('profiles').select('*').match({ id: session.user.id });
    if (profile) {
      salutation = `Ciao ${profile[0].first_name}`
    }
  }

  return (
    <html lang="it">
      <body className={inter.className}>
        <div className="mx-4 flex justify-between px-4 py-6 border border-gray-800 border-t-0 border-x-0">
          <h1 className="text-xl font-bold"><Link href={'/'}>{salutation}</Link></h1>
          {session ?
          <Logout />
            :
            <h1 className="text-xl font-bold"><Link href={'/auth'}>Login</Link></h1>
          }
        </div>
        {children}
      </body>
    </html>
  )
}
